services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php    
    tty: true
    expose:
      - ${LOCAL_PHP_EXPOSE}
    environment:
      - TZ=UTC      
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - internal
      - shared-app-network

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    depends_on:
      - php
    ports:
      - ${LOCAL_APACHE_HTTP}:80      
    environment:        
      - TZ=UTC      
      - VIRTUAL_HOST=${LOCAL_WWWROOT}
    volumes:
      - ./app:/var/www/app  
    networks:
      - internal
      - shared-app-network

  db:
    image: mariadb:lts-ubi9
    container_name: docker.mariadb    
    restart: always    
    ports:
      - ${LOCAL_DB_EXPOSE}:3306    
    environment:
      - TZ=UTC          
      - MARIADB_ROOT_PASSWORD=${LOCAL_DBPASS}
      - HOSTNAME=localhost
    volumes:
      - ./db:/var/lib/mysql 
      - ./docker/mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - internal
      # Убираем shared-app-network, если БД не нужна извне

  adminer:
    image: adminer:5.3.0
    container_name: docker.adminer    
    restart: always
    ports:
      - ${LOCAL_ADMINER_EXPOSE}:8080
    environment:
      - TZ=UTC        
    networks:
      - internal
      # Только внутренняя сеть

networks:
  # Внутренняя сеть для сервисов проекта (создаётся автоматически)
  internal:
    name: mmenu-v2_default  # Явно задаём имя для совместимости
    driver: bridge
  
  # Внешняя сеть для взаимодействия с другими проектами
  shared-app-network:
    external: true
    name: shared-app-network